---
openapi: 3.0.0
info:
  title: Billboard-API
  description: API para buscar y filtrar películas y carteleras.
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8090/api/
- url: https://proyectointegracion2021l4-04.ew.r.appspot.com/api/
tags:
- name: films
  description: Films
- name: billboard
  description: Billboard
paths:
  /films:
    get:
      tags:
      - films
      summary: Get films
      description: Get all films
      operationId: getFilms
      parameters:
      - name: order
        in: query
        description: Order results by genre, director or release
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - genre
          - -genre
          - director
          - -director
          - release
          - -release
          - duration
          - -duration
      - name: q
        in: query
        description: Query to filter
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: limit
        in: query
        description: Maximum number of results
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: offset
        in: query
        description: Offset of the results
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad request
    put:
      tags:
      - films
      summary: Update a film
      description: Update a film
      operationId: updateFilm
      requestBody:
        description: Films to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "204":
          description: Film updated
        "400":
          description: Bad request
        "404":
          description: Film not found
    post:
      tags:
      - films
      summary: Create a film
      description: Create a film
      operationId: createFilm
      requestBody:
        description: Film to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
        required: true
      responses:
        "201":
          description: Film created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_1'
        "400":
          description: Bad request
  /film/{id}:
    get:
      tags:
      - films
      summary: Get film with id
      description: Get film with id
      operationId: getFilmsId
      parameters:
      - name: id
        in: path
        description: Id of the film
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: order
        in: query
        description: Order results by genre, director or release
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - genre
          - -genre
          - director
          - -director
          - release
          - -release
          - duration
          - -duration
      - name: q
        in: query
        description: Query to filter
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: limit
        in: query
        description: Maximum number of results
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: offset
        in: query
        description: Offset of the results
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad request
    delete:
      tags:
      - films
      summary: Delete film with id
      description: Delete film with id
      operationId: deleteFilm
      parameters:
      - name: id
        in: path
        description: Id of the film
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Film deleted
        "404":
          description: Film not found
  /billboard:
    get:
      tags:
      - billboard
      summary: Get billboard
      description: Get all billboard
      operationId: getBillboard
      parameters:
      - name: order
        in: query
        description: Order results by name
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - name
          - -name
      - name: isEmpty
        in: query
        description: Filter billboard with no films
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: name
        in: query
        description: Filter billboard by name
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad request
    put:
      tags:
      - billboard
      summary: Update a billboard
      description: Update a billboard
      operationId: updateBillboard
      requestBody:
        description: Billboard to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_2'
      responses:
        "204":
          description: Billboard updated
        "400":
          description: Bad request
        "404":
          description: Billboard not found
  /billboard/{id}:
    get:
      tags:
      - billboard
      summary: Get billboard with id
      description: Get a billboard
      operationId: getBillboardId
      parameters:
      - name: id
        in: path
        description: Id of the billboard
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Billboard found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "404":
          description: Billboard not found
          
  /billboard/{billboardId}:
    post:
        tags:
        - billboard
        summary: Create billboard with id
        description: Create billboard with id
        operationId: addBillboard
        parameters:
        - name: billboardId
          in: path
          description: Id of the billboard
          required: true
          style: simple
          explode: false
          schema:
            type: string
        requestBody:
          content:
            text/plain:
              schema:
                type: string
        responses:
          "201":
            description: billboard added
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/inline_response_200_2'
          "400":
            description: Bad request
    delete:
      tags:
      - billboard
      summary: Delete billboard with id
      description: Delete billboard with id
      operationId: deleteBillboard
      parameters:
      - name: billboardId
        in: path
        description: Id of the billboard
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Film deleted from billboard
        "404":
          description: Billboard or film not found
  
  /billboard/{billboardId}/{filmId}:
    post:
      tags:
      - billboard
      summary: Add film to billboard with id
      description: Add film to billboard with id
      operationId: addFilmToBillboard
      parameters:
      - name: billboardId
        in: path
        description: Id of the billboard
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: filmId
        in: path
        description: Id of the film
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "201":
          description: Film added to billboard
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Bad request
        "404":
          description: Billboard or film not found
    delete:
      tags:
      - billboard
      summary: Delete film from billboard with id
      description: Delete film from billboard with id
      operationId: deleteFilmFromPlayist
      parameters:
      - name: billboardId
        in: path
        description: Id of the billboard
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: filmId
        in: path
        description: Id of the film
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Film deleted from billboard
        "404":
          description: Billboard or film not found
components:
  schemas:
    inline_response_200:
      required:
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        director:
          type: string
        duration:
          type: integer
        genre:
          type: string
        release:
          type: string
      example:
        id: f1
        title: Las tortugas ninjas
        director: Wilfredo
        duration: 140
        genre: ACCION
        release: 15, 10, 2021
    body:
      required:
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        director:
          type: string
        genre:
          type: string
        release:
          type: string
      example:
        id: f1
        title: Las tortugas ninjas
        director: Wilfredo
        genre: ACCION
        release: 15, 10, 2021
    body_1:
      required:
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        director:
          type: string
        genre:
          type: string
        release:
          type: string
      example:
        id: f1
        title: Las tortugas ninjas
        director: Wilfredo
        genre: ACCION
        release: 15, 10, 2021
    billboard_films:
      required:
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        director:
          type: string
        genre:
          type: string
        release:
          type: string
    inline_response_200_1:
      required:
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        films:
          type: array
          items:
            $ref: '#/components/schemas/billboard_films'
      example:
        id: p5
        name: Favourites
        description: My favourite films
        films:
        - id: f1
          title: Las tortugas ninjas
          director: Wilfredo
          genre: ACCION
          release: 15, 10, 2021
    body_2:
      required:
      - name
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        films:
          type: array
          items:
            $ref: '#/components/schemas/billboard_films'
      example:
        id: p5
        name: Favourites
        description: My favourite films
        films:
        - id: f1
          title: Las tortugas ninjas
          director: Wilfredo
          genre: ACCION
          release: 15, 10, 2021
    inline_response_200_2:
      required:
      - name
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        films:
          type: array
          items:
            required:
            - title
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              director:
                type: string
              genre:
                type: string
              release:
                type: string
      example:
        id: p5
        name: Favourites
        description: My favourite films
        films:
        - id: f1
          title: Las tortugas ninjas
          director: Wilfredo
          genre: ACCION
          release: 15, 10, 2021