openapi: 3.0.0
servers:
  - url: 'http://localhost:8090/api/'
info:
  description: API para buscar y filtrar películas y carteleras.
  version: 1.0.0
  title: Billboard-API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: films
    description: Films
  - name: billboard
    description: Billboard
paths:
  /films:
    get:
      tags:
        - films
      summary: Get films
      description: Get all films
      operationId: getFilms
      parameters:
        - name: order
          in: query
          description: Order results by genre, director or release
          required: false
          schema:
            type: string
            enum:
              - genre
              - 'genre'
              - director
              - 'director'
              - release
              - 'release'
              - duration
              - 'duration'
        - name: q
          in: query
          description: Query to filter
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description:  Maximum number of results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: offset
          in: query
          description: Offset of the results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - title
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    director:
                      type: string
                    duration:
                      type: integer
                    genre:
                      type: string
                    release:
                      type: string
                  example:
                    id: f1
                    title: Las tortugas ninjas
                    director: Wilfredo
                    duration: 140
                    genre: 'ACCION'
                    release: '15, 10, 2021'
        '400':
          description: Bad request
    post:
      tags:
        - films
      summary: Create a film
      description: Create a film
      operationId: createFilm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                id:
                  type: string
                title:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                release:
                  type: string
              example:
                id: f1
                title: Las tortugas ninjas
                director: Wilfredo
                genre: 'ACCION'
                release: '15, 10, 2021'
        description: Film to create
        required: true
      responses:
        '201':
          description: Film created
          content:
            application/json:
              schema:
                type: object
                required:
                  - title
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  director:
                    type: string
                  genre:
                    type: string
                  release:
                    type: string
                example:
                  id: f1
                  title: Las tortugas ninjas
                  director: Wilfredo
                  genre: 'ACCION'
                  release: '15, 10, 2021'
        '400':
          description: Bad request
  '/films':
  
    put:
      tags:
        - films
      summary: Update a film
      description: Update a film
      operationId: updateFilm
      requestBody:
        content:
          application/json:
            schema:
                type: object
                required:
                  - title
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  director:
                    type: string
                  genre:
                    type: string
                  release:
                    type: string
                example:
                  id: f1
                  title: Las tortugas ninjas
                  director: Wilfredo
                  genre: 'ACCION'
                  release: '15, 10, 2021'
        description: Films to update
      responses:
        '204':
          description: Film updated
        '400':
          description: Bad request
        '404':
          description: Film not found
  '/film/{id}':
    delete:
      tags:
        - films
      summary: Delete film
      description: Delete film
      operationId: deleteFilm
      parameters:
        - name: id
          in: path
          description: Id of the film
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Film deleted
        '404':
          description: Film not found
  /billboard:
    get:
      tags:
        - billboard
      summary: Get billboard
      description: Get all billboard
      operationId: getBillboard
      parameters:
        - name: order
          in: query
          description: Order results by name
          required: false
          schema:
            type: string
            enum:
              - name
              - '-name'
        - name: isEmpty
          in: query
          description: Filter billboard with no films
          required: false
          schema:
            type: boolean
        - name: name
          in: query
          description: Filter billboard by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    films:
                      type: array
                      items:
                        type: object
                        required:
                          - title
                        properties:
                          id:
                            type: string
                          title:
                            type: string
                          director:
                            type: string
                          genre:
                            type: string
                          release:
                            type: string
                  example:
                    id: p5
                    name: Favourites
                    description: My favourite films
                    films:
                      - id: f1
                        title: Las tortugas ninjas
                        director: Wilfredo
                        genre: 'ACCION'
                        release: '15, 10, 2021'
        '400':
          description: Bad request
    put:
      tags:
        - billboard
      summary: Update a billboard
      description: Update a billboard
      operationId: updateBillboard
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
              properties:
                id:
                  type: string
                name:
                  type: string
                description:
                  type: string
                films:
                  type: array
                  items:
                    type: object
                    required:
                      - title
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      director:
                        type: string
                      genre:
                        type: string
                      release:
                        type: string
              example:
                id: p5
                name: Favourites
                description: My favourite films
                films:
                  - id: f1
                    title: Las tortugas ninjas
                    director: Wilfredo
                    genre: 'ACCION'
                    release: '15, 10, 2021'
        description: Billboard to update
      responses:
        '204':
          description: Billboard updated
        '400':
          description: Bad request
        '404':
          description: Billboard not found
  '/billboard/{id}':
    get:
      tags:
        - billboard
      summary: Get a billboard
      description: Get a billboard
      operationId: getBillboard
      parameters:
        - name: id
          in: path
          description: Id of the billboard
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Billboard found
          content:
            application/json:
              schema:
                required:
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  films:
                    type: array
                    items:
                      type: object
                      required:
                        - title
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        director:
                          type: string
                        genre:
                          type: string
                        release:
                          type: string
                example:
                  id: p5
                  name: Favourites
                  description: My favourite films
                  films:
                    - id: f1
                      title: Las tortugas ninjas
                      director: Wilfredo
                      genre: 'ACCION'
                      release: '15, 10, 2021'
        '404':
          description: Billboard not found
  '/billboard/{billboardId}/{filmId}':
    post:
      tags:
        - billboard
      summary: Add film to billboard
      description: Add film to billboard
      operationId: addFilmToBillboard
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - name: billboardId
          in: path
          description: Id of the billboard
          required: true
          schema:
            type: string
        - name: filmId
          in: path
          description: Id of the film
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Film added to billboard
          content:
            application/json:
              schema:
                required:
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  films:
                    type: array
                    items:
                      type: object
                      required:
                        - title
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        director:
                          type: string
                        genre:
                          type: string
                        release:
                          type: string
                example:
                  id: p5
                  name: Favourites
                  description: My favourite films
                  films:
                    - id: f1
                      title: Las tortugas ninjas
                      director: Wilfredo
                      genre: 'ACCION'
                      release: '15, 10, 2021'
        '400':
          description: Bad request
        '404':
          description: Billboard or film not found
    delete:
      tags:
        - billboard
      summary: Delete film from billboard
      description: Delete film from billboard
      operationId: deleteFilmFromPlayist
      parameters:
        - name: billboardId
          in: path
          description: Id of the billboard
          required: true
          schema:
            type: string
        - name: filmId
          in: path
          description: Id of the film
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Film deleted from billboard
        '404':
          description: Billboard or film not found